import datetime
import os
import requests

import search_utils as utils
import prompt_utils as prompts
from langchain_core.messages import HumanMessage, SystemMessage, filter_messages
from tavily import TavilyClient
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field


class SummaryOutput(BaseModel):
    """Schema for webpage content summarization."""
    summary: str = Field(description="Concise summary of the webpage content")
    key_excerpts: str = Field(description="Important quotes and excerpts")

def get_today_str() -> str:
    """Get current date in a human-readable format."""
    return datetime.datetime.now().strftime("%a %b %-d, %Y")


def tavily_search(query:str, max_results: int = 3, include_raw_content=True, topic: str = "general", **kw):
    tavily_api_key = os.environ.get("TAVILY_API_KEY")
    if tavily_api_key is None:
        r = requests.post(os.environ.get("TAVILY_BASE_URL"),
                        json={"query": query, "max_results": max_results, "include_raw_content": include_raw_content, "topic": topic, **kw}, timeout=60)
        r.raise_for_status()
        return r.json()
    else:
        tavily_client = TavilyClient(api_key=tavily_api_key)

        return tavily_client.search(
            query=query,
            max_results=max_results,
            include_raw_content=include_raw_content,
            topic=topic,
            **kw
        )

def web_search(query: str, max_results: int = 3) -> str:
    """Search the web for information about a specific query.
    
    Args:
        query: The search query (be specific for better results)
        max_results: Number of results to return (1-5)
        
    Returns:
        Formatted search results with sources
    """
    print(f"🔍 Searching: {query}")
    
    result = tavily_search(
        query,
        max_results=max_results,
        include_raw_content=True,
        topic="general"
    )
    
    unique_results = {}
    for res in result.get('results', []):
        url = res.get('url')
        if not url or url in unique_results:
            continue

        raw_content = res.get('raw_content')
        fallback_content = res.get('content') or ""
        content = summarize_webpage_content(raw_content or fallback_content)

        unique_results[url] = {
            'title': res.get('title', 'Untitled Source'),
            'content': content
        }
    
    if not unique_results:
        return "No results found."
    
    output = f"Search results for: '{query}'\n\n"
    for i, (url, data) in enumerate(unique_results.items(), 1):
        output += f"\n--- SOURCE {i}: {data['title']} ---\n"
        output += f"URL: {url}\n\n{data['content']}\n\n" + "-"*80 + "\n"
    
    return output


def summarize_webpage_content(webpage_content:str) -> str:
    """Summarize webpage content."""
    if not webpage_content:
        return "No content available from this source."

    if not isinstance(webpage_content, str):
        webpage_content = str(webpage_content)


    try:
        summarization_model = ChatOpenAI(
            model=os.environ.get("OPENAI_MODEL"),
            base_url=os.environ.get("OPENAI_BASE_URL"),
        ).with_structured_output(SummaryOutput)


        system_prompt = prompts.summarize_webpage.format(date=utils.get_today_str(), webpage_content=webpage_content)


        summary = summarization_model.invoke([
            HumanMessage(content=system_prompt)
        ])

        return (
            f"<summary>\n{summary.summary}\n</summary>\n\n"
            f"<key_excerpts>\n{summary.key_excerpts}\n</key_excerpts>"
        )
    except Exception as e:
        print(f"Summarization failed: {e}")
        trimmed = webpage_content if len(webpage_content) <= 1000 else webpage_content[:1000] + "..."
        return trimmed
    



def extract_research_notes(messages:list):
    """
    Extract research notes from the conversation messages.
    Filters messages to include only those generated by tools or the AI.
    """

    raw_notes = [
            str(m.content) for m in filter_messages(
                messages, 
                include_types=["tool", "ai"]
            )
        ]
    return "\n".join(raw_notes)
